import { InventoryItem, AssetDelivery, AssetStatus, HistoryLog, DiscardLog, ItemCondition } from "./types";

export const INITIAL_INVENTORY: InventoryItem[] = [
  {
    id: "inv-1",
    name: "Notebook Dell Latitude 3420 i7 16GB",
    code: "PAT-00892",
    category: "Notebooks",
    totalQuantity: 15,
    availableQuantity: 11,
  },
  {
    id: "inv-2",
    name: "Monitor Dell Professional 24\" P2422H",
    code: "PAT-01450",
    category: "Monitores",
    totalQuantity: 20,
    availableQuantity: 15,
  },
  {
    id: "inv-3",
    name: "Smartphone Samsung Galaxy S23 256GB",
    code: "PAT-02203",
    category: "Celulares",
    totalQuantity: 8,
    availableQuantity: 6,
  },
  {
    id: "inv-4",
    name: "Headset Jabra Evolve2 40 USB",
    code: "PAT-03310",
    category: "Periféricos",
    totalQuantity: 25,
    availableQuantity: 21,
  },
  {
    id: "inv-5",
    name: "Teclado e Mouse Logitech Sem Fio MK270",
    code: "PAT-00911",
    category: "Periféricos",
    totalQuantity: 30,
    availableQuantity: 28,
  },
  {
    id: "inv-6",
    name: "MacBook Pro 14\" M2 16GB 512GB",
    code: "PAT-00770",
    category: "Notebooks",
    totalQuantity: 5,
    availableQuantity: 3,
  },
];

export const INITIAL_DELIVERIES: AssetDelivery[] = [
  {
    id: "del-1",
    itemId: "inv-1",
    itemName: "Notebook Dell Latitude 3420 i7 16GB",
    code: "PAT-00892",
    quantity: 1,
    colaborador: "Mariana Souza Santos",
    setor: "Tecnologia da Informação",
    dataEntrega: "2026-05-10",
    motivo: "Nova colaboradora devops contratação CLT",
    observacao: "Entregue com mochila, carregador e mousepad.",
    status: AssetStatus.EmUso,
  },
  {
    id: "del-2",
    itemId: "inv-1",
    itemName: "Notebook Dell Latitude 3420 i7 16GB",
    code: "PAT-00892",
    quantity: 1,
    colaborador: "Carlos Eduardo Lima",
    setor: "Financeiro",
    dataEntrega: "2026-04-18",
    motivo: "Substituição de equipamento antigo danificado",
    observacao: "O notebook antigo foi enviado para descarte devido à placa mãe queimada.",
    status: AssetStatus.EmUso,
  },
  {
    id: "del-3",
    itemId: "inv-2",
    itemName: "Monitor Dell Professional 24\" P2422H",
    code: "PAT-01450",
    quantity: 2,
    colaborador: "Ana Julia Moreira",
    setor: "Design & UX",
    dataEntrega: "2026-05-02",
    motivo: "Setup de duas telas para edição audiovisual",
    status: AssetStatus.EmUso,
  },
  {
    id: "del-4",
    itemId: "inv-3",
    itemName: "Smartphone Samsung Galaxy S23 256GB",
    code: "PAT-02203",
    quantity: 1,
    colaborador: "Fernanda Ribeiro",
    setor: "Vendas Externas",
    dataEntrega: "2026-05-20",
    motivo: "Comunicação corporativa operacional",
    observacao: "Chip da operadora Claro já instalado.",
    status: AssetStatus.EmUso,
  },
  {
    id: "del-5",
    itemId: "inv-4",
    itemName: "Headset Jabra Evolve2 40 USB",
    code: "PAT-03310",
    quantity: 1,
    colaborador: "Lucas Andrade Neves",
    setor: "Atendimento ao Cliente",
    dataEntrega: "2026-03-12",
    motivo: "Substituição de headset analógico antigo",
    status: AssetStatus.Devolvido,
    dataDevolucao: "2026-06-01",
    condicaoDevolucao: ItemCondition.Excelente,
    observacao: "Devolvido por motivo de desligamento do colaborador.",
  },
  {
    id: "del-6",
    itemId: "inv-5",
    itemName: "Teclado e Mouse Logitech Sem Fio MK270",
    code: "PAT-00911",
    quantity: 1,
    colaborador: "Rodrigo Almeida",
    setor: "Recursos Humanos",
    dataEntrega: "2026-05-25",
    motivo: "Montagem de home-office parcial",
    status: AssetStatus.EmManutencao,
    observacao: "Apresentou falha intermitente na conexão USB do mouse. Retornado para testes na TI.",
  },
  {
    id: "del-7",
    itemId: "inv-6",
    itemName: "MacBook Pro 14\" M2 16GB 512GB",
    code: "PAT-00770",
    quantity: 1,
    colaborador: "Roberto Silveira Neto",
    setor: "Tecnologia da Informação",
    dataEntrega: "2026-02-15",
    motivo: "Equipamento de desenvolvimento de apps iOS",
    status: AssetStatus.Descartado,
    observacao: "Aparelho sofreu queda grave com perda total da carcaça e tela. Enviado ao descarte.",
  },
];

export const INITIAL_HISTORY: HistoryLog[] = [
  {
    id: "hist-1",
    timestamp: "2026-02-15T09:30:00Z",
    action: "Entrega",
    itemName: "MacBook Pro 14\" M2 16GB 512GB",
    code: "PAT-00770",
    colaborador: "Roberto Silveira Neto",
    setor: "Tecnologia da Informação",
    quantity: 1,
    details: "Entregue MacBook Pro para desenvolvimento iOS. Motivo: Contratação de Tech Lead.",
  },
  {
    id: "hist-2",
    timestamp: "2026-03-12T14:15:00Z",
    action: "Entrega",
    itemName: "Headset Jabra Evolve2 40 USB",
    code: "PAT-03310",
    colaborador: "Lucas Andrade Neves",
    setor: "Atendimento ao Cliente",
    quantity: 1,
    details: "Entregue novo headset Jabra para suporte.",
  },
  {
    id: "hist-3",
    timestamp: "2026-04-18T10:00:00Z",
    action: "Entrega",
    itemName: "Notebook Dell Latitude 3420 i7 16GB",
    code: "PAT-00892",
    colaborador: "Carlos Eduardo Lima",
    setor: "Financeiro",
    quantity: 1,
    details: "Entrega de notebook. Motivo: Substituição de equipamento antigo danificado.",
  },
  {
    id: "hist-4",
    timestamp: "2026-05-02T11:00:00Z",
    action: "Entrega",
    itemName: "Monitor Dell Professional 24\" P2422H",
    code: "PAT-01450",
    colaborador: "Ana Julia Moreira",
    setor: "Design & UX",
    quantity: 2,
    details: "Entrega de 2 monitores Dell para estação de edição.",
  },
  {
    id: "hist-5",
    timestamp: "2026-05-10T15:20:00Z",
    action: "Entrega",
    itemName: "Notebook Dell Latitude 3420 i7 16GB",
    code: "PAT-00892",
    colaborador: "Mariana Souza Santos",
    setor: "Tecnologia da Informação",
    quantity: 1,
    details: "Entrega inicial para onboarding DevOps.",
  },
  {
    id: "hist-6",
    timestamp: "2026-05-20T08:45:00Z",
    action: "Entrega",
    itemName: "Smartphone Samsung Galaxy S23 256GB",
    code: "PAT-02203",
    colaborador: "Fernanda Ribeiro",
    setor: "Vendas Externas",
    quantity: 1,
    details: "Atribuição de smartphone corporativo para rota comercial.",
  },
  {
    id: "hist-7",
    timestamp: "2026-05-25T16:00:00Z",
    action: "Entrega",
    itemName: "Teclado e Mouse Logitech Sem Fio MK270",
    code: "PAT-00911",
    colaborador: "Rodrigo Almeida",
    setor: "Recursos Humanos",
    quantity: 1,
    details: "Combo teclado e mouse para home-office.",
  },
  {
    id: "hist-8",
    timestamp: "2026-05-27T10:30:00Z",
    action: "Manutenção",
    itemName: "Teclado e Mouse Logitech Sem Fio MK270",
    code: "PAT-00911",
    colaborador: "Rodrigo Almeida",
    setor: "Recursos Humanos",
    quantity: 1,
    details: "Alterado status para Em Manutenção devido à falha intermitente no mouse bluetooth.",
  },
  {
    id: "hist-9",
    timestamp: "2026-06-01T14:00:00Z",
    action: "Devolução",
    itemName: "Headset Jabra Evolve2 40 USB",
    code: "PAT-03310",
    colaborador: "Lucas Andrade Neves",
    setor: "Atendimento ao Cliente",
    quantity: 1,
    details: "Equipamento devolvido em excelente estado. Motivo: Desligamento voluntário do colaborador.",
  },
  {
    id: "hist-10",
    timestamp: "2026-06-02T11:50:00Z",
    action: "Descarte",
    itemName: "MacBook Pro 14\" M2 16GB 512GB",
    code: "PAT-00770",
    colaborador: "Roberto Silveira Neto",
    setor: "Tecnologia da Informação",
    quantity: 1,
    details: "Enviado para descarte após queda grave inviabilizar conserto. Placa lógica trincada.",
  }
];

export const INITIAL_DISCARDS: DiscardLog[] = [
  {
    id: "dis-1",
    deliveryId: "del-7",
    itemName: "MacBook Pro 14\" M2 16GB 512GB",
    code: "PAT-00770",
    quantity: 1,
    colaboradorOriginal: "Roberto Silveira Neto",
    setorOriginal: "Tecnologia da Informação",
    dataDescarte: "2026-06-02",
    condicao: "Danificado",
    motivo: "Perda total por queda acidental drástica de escada. Assistência técnica laudou irreparável.",
    observacao: "Bateria foi removida e enviada para reciclagem verde apropriada."
  }
];

export const SECTORS = [
  "Tecnologia da Informação",
  "Financeiro",
  "Design & UX",
  "Vendas Externas",
  "Recursos Humanos",
  "Atendimento ao Cliente",
  "Marketing",
  "Operações",
  "Jurídico",
  "Engenharia"
];
